language: python
python: "3.8"
install: pipenv install --dev
script: pytest --cov .
after_success: coveralls
env:
  - FLASK_ENV=development
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxtYXJjbzg5JTNBbWF0cml4Lm9yZy8lMjFLbmNSTEV5ak1TTUdmWGRDT2IlM0FtYXRyaXgub3Jn"
    on_success: always  # always|never|change
    on_failure: always
    on_start: never
