version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6378:6379"
  postgresql:
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
